#!/bin/bash
# =============================================================================
# setup-onboarding.sh — OpenTAK Onboarding Portal (Docker)
# =============================================================================
# Version:    1.0.0
# Date:       2026-04-08
# Source:     https://github.com/mattronix/opentak-onboarding-portal
#
# What the script does:
#   1. Pulls the onboarding portal Docker image
#   2. Creates install directory with .env and docker-compose.yml
#   3. Starts the portal container (port 5050 → 5000 internal)
#   4. Creates nginx reverse proxy config
#   5. Obtains Let's Encrypt cert (standalone, same pattern as CloudTAK)
#   6. Rewrites nginx with HTTPS
#
# Usage:
#   Run as root:
#     bash /opt/scripts/setup-onboarding.sh
#
#   Or with explicit domain:
#     bash /opt/scripts/setup-onboarding.sh portal.example.com
#
# Requirements:
#   - OpenTAK Server installed and running (port 443 with LE cert)
#   - Docker installed
#   - DNS A record for the portal domain
#   - Port 80 and 443 open
#   - config.env with PORTAL_DOMAIN and OTS_DOMAIN set
# =============================================================================
set -euo pipefail

# ── Load config ──
CONFIG_ENV="/opt/scripts/config.env"
if [[ -f "$CONFIG_ENV" ]]; then
  source "$CONFIG_ENV"
fi

PORTAL_DOMAIN="${1:-${PORTAL_DOMAIN:-}}"
OTS_DOMAIN="${OTS_DOMAIN:-}"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[✔]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
info() { echo -e "${CYAN}[i]${NC} $*"; }
err()  { echo -e "${RED}[✘]${NC} $*"; exit 1; }

# ── Validate ──
[[ $EUID -eq 0 ]] || err "Must be run as root"
[[ -n "$PORTAL_DOMAIN" ]] || err "PORTAL_DOMAIN not set — check config.env or pass as argument"
[[ -n "$OTS_DOMAIN" ]] || err "OTS_DOMAIN not set — check config.env"
command -v docker &>/dev/null || err "Docker not installed"

INSTALL_DIR="/opt/onboarding-portal"
PORTAL_HOST_PORT="5050"
DOCKER_IMAGE="mattronix/atak-onboarding-portal"

echo ""
echo "============================================"
echo " OpenTAK Onboarding Portal — Setup"
echo " Portal:  ${PORTAL_DOMAIN}"
echo " OTS:     ${OTS_DOMAIN}"
echo " Port:    ${PORTAL_HOST_PORT} → 5000"
echo "============================================"
echo ""

# ── 1. Pull Docker image ──
info "Pulling Docker image: ${DOCKER_IMAGE}..."
docker pull "$DOCKER_IMAGE"
log "Docker image pulled"

# ── 2. Create install directory ──
info "Creating install directory: ${INSTALL_DIR}"
mkdir -p "${INSTALL_DIR}/instance" "${INSTALL_DIR}/datapackages"

# ── 3. Generate .env ──
if [[ -f "${INSTALL_DIR}/.env" ]]; then
  warn ".env already exists — keeping existing config"
else
  SECRET_KEY=$(openssl rand -hex 32)
  JWT_SECRET=$(openssl rand -hex 32)

  cat > "${INSTALL_DIR}/.env" << ENV_EOF
# Generated by setup-onboarding.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
SECRET_KEY=${SECRET_KEY}
JWT_SECRET_KEY=${JWT_SECRET}

# OpenTAK Server connection (port 443 — LE cert, no mTLS)
OTS_URL=https://${OTS_DOMAIN}
OTS_USERNAME=administrator
OTS_PASSWORD=password
OTS_VERIFY_SSL=True

# Application
DEBUG=False
SQLALCHEMY_DATABASE_URI=sqlite:///db.sqlite
FRONTEND_URL=https://${PORTAL_DOMAIN}
CORS_ORIGINS=*

# Email (disabled by default — edit to enable)
MAIL_ENABLED=False

# Storage
DATAPACKAGE_UPLOAD_FOLDER=datapackages
UPDATES_UPLOAD_FOLDER=updates
ENV_EOF
  log ".env generated with random secrets"
fi

# ── 4. Create docker-compose.yml ──
if [[ -f "${INSTALL_DIR}/docker-compose.yml" ]]; then
  warn "docker-compose.yml already exists — keeping existing config"
else
  cat > "${INSTALL_DIR}/docker-compose.yml" << 'COMPOSE_EOF'
services:
  web:
    restart: always
    image: mattronix/atak-onboarding-portal
    ports:
      - "5050:5000"
    env_file:
      - .env
    volumes:
      - ./instance:/app/instance
      - ./datapackages:/app/datapackages
    environment:
      - CORS_ORIGINS=*
    extra_hosts:
      - "host.docker.internal:host-gateway"
COMPOSE_EOF
  log "docker-compose.yml created"
fi

# ── 5. Start containers ──
info "Starting onboarding portal container..."
cd "$INSTALL_DIR"
docker compose up -d
log "Onboarding portal container started on port ${PORTAL_HOST_PORT}"

# Wait for the portal to respond
info "Waiting for portal to respond (max 60s)..."
for i in {1..30}; do
  if curl -sf "http://localhost:${PORTAL_HOST_PORT}/" > /dev/null 2>&1; then
    log "Portal responding on :${PORTAL_HOST_PORT}"
    break
  fi
  if [[ $i -eq 30 ]]; then
    warn "Portal did not respond after 60s — continuing anyway"
  fi
  sleep 2
done

# ── 6. Create nginx config (HTTP first) ──
NGINX_CONF="/etc/nginx/sites-available/onboarding-portal"

if [[ -f "$NGINX_CONF" ]]; then
  warn "nginx config already exists: ${NGINX_CONF}"
  cp "$NGINX_CONF" "${NGINX_CONF}.backup.$(date +%Y%m%d-%H%M%S)"
fi

tee "$NGINX_CONF" > /dev/null << 'PORTAL_NGINX_EOF'
server {
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name __PORTAL_DOMAIN__;

    location / {
        proxy_pass http://localhost:5050;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    listen 80;
}
PORTAL_NGINX_EOF

sed -i "s/__PORTAL_DOMAIN__/${PORTAL_DOMAIN}/g" "$NGINX_CONF"
log "nginx config created: ${NGINX_CONF}"

if [[ ! -L /etc/nginx/sites-enabled/onboarding-portal ]]; then
  ln -s "$NGINX_CONF" /etc/nginx/sites-enabled/onboarding-portal
  log "nginx site enabled (symlink)"
else
  log "nginx site already enabled"
fi

# Install certbot if missing
if ! command -v certbot &>/dev/null; then
  apt-get install -y certbot python3-certbot-nginx
  log "certbot installed"
fi

nginx -t 2>&1 || err "nginx config has errors — check ${NGINX_CONF}"
log "nginx config OK"
if systemctl is-active --quiet nginx; then
  systemctl reload nginx
  log "nginx reloaded"
else
  systemctl start nginx
  log "nginx started (was not active)"
fi

# ── 7. Let's Encrypt for the portal domain ──
# Same standalone pattern as CloudTAK — avoids certbot rewriting OTS nginx configs.
echo ""
info "Obtaining Let's Encrypt certificate for portal (standalone)..."
systemctl stop nginx

certbot certonly \
  --standalone \
  --non-interactive \
  --agree-tos \
  --cert-name onboarding-portal \
  --email "admin@${PORTAL_DOMAIN}" \
  -d "${PORTAL_DOMAIN}"
log "Let's Encrypt cert obtained for ${PORTAL_DOMAIN}"

LE_PORTAL_CERT="/etc/letsencrypt/live/onboarding-portal/fullchain.pem"
LE_PORTAL_KEY="/etc/letsencrypt/live/onboarding-portal/privkey.pem"

# ── 8. Rewrite nginx config with SSL ──
tee "$NGINX_CONF" > /dev/null << 'PORTAL_SSL_EOF'
# HTTP → HTTPS redirect
server {
    listen 80;
    server_name __PORTAL_DOMAIN__;
    return 301 https://$host$request_uri;
}

# Onboarding Portal HTTPS
server {
    listen 443 ssl;
    server_name __PORTAL_DOMAIN__;

    ssl_certificate __LE_CERT__;
    ssl_certificate_key __LE_KEY__;
    add_header Strict-Transport-Security "max-age=63072000" always;

    location / {
        proxy_pass http://localhost:5050;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
PORTAL_SSL_EOF

sed -i "s|__PORTAL_DOMAIN__|${PORTAL_DOMAIN}|g" "$NGINX_CONF"
sed -i "s|__LE_CERT__|${LE_PORTAL_CERT}|g" "$NGINX_CONF"
sed -i "s|__LE_KEY__|${LE_PORTAL_KEY}|g" "$NGINX_CONF"
log "nginx SSL config created for portal"

nginx -t 2>&1 || err "nginx SSL config has errors"
systemctl start nginx
log "nginx started with SSL"

echo ""
log "Onboarding Portal setup complete!"
info "URL: https://${PORTAL_DOMAIN}"
info "Login with your OTS admin credentials"
echo ""
